Update .devops/code-review-pipelines.yml
Co-authored-by: Pasquale De Vita <59291437+pasqualedevita@users.noreply.github.com>

diff --git a/.devops/code-review-pipelines.yml b/.devops/code-review-pipelines.yml
--- a/.devops/code-review-pipelines.yml
+++ b/.devops/code-review-pipelines.yml
@@ -69,5 +69,6 @@ stages:
                 set -e
                 cd src/psql/selfcare/subscription-migrations
                 echo "Validating migrations"
-                ./flyway.sh validate PROD-IO db && echo "Validation successful" || { echo "Validation failed"; exit 1; }
+                ./flyway.sh validate PROD-IO db -ignorePendingMigrations=true && echo "Validation successful" || { echo "Validation failed"; exit 1; }
+                ./flyway.sh info PROD-IO db && echo "Info successful" || { echo "Info failed"; exit 1; }
                 echo $administrator_login
