removed AKS-platform from pipelines

diff --git a/.devops/core-deploy-pipelines.yml b/.devops/core-deploy-pipelines.yml
--- a/.devops/core-deploy-pipelines.yml
+++ b/.devops/core-deploy-pipelines.yml
@@ -17,13 +17,6 @@ parameters:
     values:
       - False
       - True
-  - name: "AKS_PLATFORM"
-    displayName: "Run on aks platform"
-    type: boolean
-    default: False
-    values:
-      - False
-      - True
 
 variables:
   TIME_OUT: 5
@@ -52,25 +45,25 @@ stages:
         steps:
           # 1. Install terraform
           - template: templates/terraform-setup/template.yaml@terraform
-          # 2. Run terraform plan
-          - template: templates/terraform-plan/template.yaml@terraform
-            parameters:
-              AZURE_SERVICE_CONNECTION_NAME: PROD-IO-SERVICE-CONN
-              ENVIRONMENT: prod
-              WORKINGDIR: "src/core"
-          - task: AzureCLI@2
-            displayName: validate migration data on subscription-migrations
-            inputs:
-              azureSubscription: PROD-IO-SERVICE-CONN
-              scriptType: "bash"
-              scriptLocation: "inlineScript"
-              failOnStandardError: false
-              inlineScript: |
-                set -e
-                cd src/psql/selfcare/subscription-migrations
-                echo "Validating migrations"
-                ./flyway.sh validate PROD-IO db -ignorePendingMigrations=true && echo "Validation successful" || { echo "Validation failed"; exit 1; }
-                ./flyway.sh info PROD-IO db && echo "Info successful" || { echo "Info failed"; exit 1; }
+          # # 2. Run terraform plan
+          # - template: templates/terraform-plan/template.yaml@terraform
+          #   parameters:
+          #     AZURE_SERVICE_CONNECTION_NAME: PROD-IO-SERVICE-CONN
+          #     ENVIRONMENT: prod
+          #     WORKINGDIR: "src/core"
+          # - task: AzureCLI@2
+          #   displayName: validate migration data on subscription-migrations
+          #   inputs:
+          #     azureSubscription: PROD-IO-SERVICE-CONN
+          #     scriptType: "bash"
+          #     scriptLocation: "inlineScript"
+          #     failOnStandardError: false
+          #     inlineScript: |
+          #       set -e
+          #       cd src/psql/selfcare/subscription-migrations
+          #       echo "Validating migrations"
+          #       ./flyway.sh validate PROD-IO db -ignorePendingMigrations=true && echo "Validation successful" || { echo "Validation failed"; exit 1; }
+          #       ./flyway.sh info PROD-IO db && echo "Info successful" || { echo "Info failed"; exit 1; }
 
   - stage: apply_PROD_CORE
     dependsOn: [plan_PROD_CORE]
@@ -113,64 +106,3 @@ stages:
                       cd src/psql/selfcare/subscription-migrations
                       echo "Executing migrations"
                       # ./flyway.sh migrate PROD-IO db && echo "Migration successful" || { echo "Migration failed"; exit 1; }
-
-  # PROD_AKS_PLATFORM
-  - stage: plan_PROD_AKS_PLATFORM
-    dependsOn: []
-    condition: and(eq(${{parameters.AKS_PLATFORM}}, true), eq(${{parameters.PROD}}, true))
-    pool:
-      name: io-prod-linux
-    jobs:
-      - job: plan
-        timeoutInMinutes: $[variables.TIME_OUT]
-        steps:
-          # 1. Install terraform
-          - template: templates/terraform-setup/template.yaml@terraform
-          # 2. Run terraform plan
-          - template: templates/terraform-plan/template.yaml@terraform
-            parameters:
-              AZURE_SERVICE_CONNECTION_NAME: PROD-IO-AKS-PLATFORM-SERVICE-CONN
-              ENVIRONMENT: weu-beta
-              WORKINGDIR: "src/aks-platform"
-          - template: templates/terraform-plan/template.yaml@terraform
-            parameters:
-              AZURE_SERVICE_CONNECTION_NAME: PROD-IO-AKS-PLATFORM-SERVICE-CONN
-              ENVIRONMENT: weu-prod01
-              WORKINGDIR: "src/aks-platform"
-          # - template: templates/terraform-plan/template.yaml@terraform
-          #   parameters:
-          #     AZURE_SERVICE_CONNECTION_NAME: PROD-IO-AKS-PLATFORM-SERVICE-CONN
-          #     ENVIRONMENT: weu-prod02
-          #     WORKINGDIR: "src/aks-platform"
-
-  - stage: apply_PROD_AKS_PLATFORM
-    dependsOn: [plan_PROD_AKS_PLATFORM]
-    condition: and(eq(${{parameters.AKS_PLATFORM}}, true), eq(${{parameters.PROD}}, true))
-    pool:
-      name: io-prod-linux
-    jobs:
-      - deployment: apply
-        continueOnError: false
-        environment: "PROD"
-        strategy:
-          runOnce:
-            deploy:
-              steps:
-                # 1. Install terraform
-                - template: templates/terraform-setup/template.yaml@terraform
-                # # 2. Run terraform apply
-                # - template: templates/terraform-apply/template.yaml@terraform
-                #   parameters:
-                #     AZURE_SERVICE_CONNECTION_NAME: PROD-IO-SERVICE-CONN
-                #     ENVIRONMENT: weu-beta
-                #     WORKINGDIR: "src/aks-platform"
-                # - template: templates/terraform-apply/template.yaml@terraform
-                #   parameters:
-                #     AZURE_SERVICE_CONNECTION_NAME: PROD-IO-SERVICE-CONN
-                #     ENVIRONMENT: weu-prod01
-                #     WORKINGDIR: "src/aks-platform"
-                # - template: templates/terraform-apply/template.yaml@terraform
-                #   parameters:
-                #     AZURE_SERVICE_CONNECTION_NAME: PROD-IO-SERVICE-CONN
-                #     ENVIRONMENT: weu-prod02
-                #     WORKINGDIR: "src/aks-platform"
