[#IOPSC-61] Create db schema for `devportalservicedata-db-postgresql` (#257)

diff --git a/.devops/core-code-review-pipelines.yml b/.devops/core-code-review-pipelines.yml
--- a/.devops/core-code-review-pipelines.yml
+++ b/.devops/core-code-review-pipelines.yml
@@ -51,7 +51,7 @@ stages:
               AZURE_SERVICE_CONNECTION_NAME: PROD-IO-SERVICE-CONN
               ENVIRONMENT: prod
               WORKINGDIR: "src/core"
-      - job: validate_sql_migration
+      - job: validate_sql_migration__subscription_migrations
         steps:
           - task: AzureCLI@2
             displayName: validate migration data on subscription-migrations
@@ -63,6 +63,21 @@ stages:
               inlineScript: |
                 set -e
                 cd src/psql/selfcare/subscription-migrations
+                echo "Validating migrations"
+                ./flyway.sh validate PROD-IO db -ignorePendingMigrations=true && echo "Validation successful" || { echo "Validation failed"; exit 1; }
+                ./flyway.sh info PROD-IO db && echo "Info successful" || { echo "Info failed"; exit 1; }
+      - job: validate_sql_migration__devportal_servicedata
+        steps:
+          - task: AzureCLI@2
+            displayName: validate migration data on devportal-service-data
+            inputs:
+              azureSubscription: PROD-IO-SERVICE-CONN
+              scriptType: "bash"
+              scriptLocation: "inlineScript"
+              failOnStandardError: false
+              inlineScript: |
+                set -e
+                cd src/psql/selfcare/devportal-service-data
                 echo "Validating migrations"
                 ./flyway.sh validate PROD-IO db -ignorePendingMigrations=true && echo "Validation successful" || { echo "Validation failed"; exit 1; }
                 ./flyway.sh info PROD-IO db && echo "Info successful" || { echo "Info failed"; exit 1; }
